# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\alca0\Documents\Python_Scripts\dicom_ui\dicom_ui_design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1017, 868)
        Dialog.setAcceptDrops(False)
        Dialog.setAutoFillBackground(False)
        self.load_button = QtWidgets.QPushButton(Dialog)
        self.load_button.setGeometry(QtCore.QRect(20, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.load_button.setFont(font)
        self.load_button.setObjectName("load_button")
        self.img_slider = QtWidgets.QSlider(Dialog)
        self.img_slider.setEnabled(False)
        self.img_slider.setGeometry(QtCore.QRect(20, 800, 771, 20))
        self.img_slider.setMinimum(0)
        self.img_slider.setMaximum(10)
        self.img_slider.setPageStep(2)
        self.img_slider.setProperty("value", 0)
        self.img_slider.setOrientation(QtCore.Qt.Horizontal)
        self.img_slider.setObjectName("img_slider")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 831, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setSpacing(0)
        self.layout.setObjectName("layout")
        self.slice = QtWidgets.QLabel(Dialog)
        self.slice.setGeometry(QtCore.QRect(800, 780, 55, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.slice.setFont(font)
        self.slice.setText("")
        self.slice.setObjectName("slice")
        self.warning_label = QtWidgets.QLabel(Dialog)
        self.warning_label.setGeometry(QtCore.QRect(860, 760, 161, 41))
        self.warning_label.setText("")
        self.warning_label.setObjectName("warning_label")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(20, 830, 831, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gamma_slider = QtWidgets.QSlider(Dialog)
        self.gamma_slider.setEnabled(False)
        self.gamma_slider.setGeometry(QtCore.QRect(880, 90, 22, 681))
        self.gamma_slider.setMinimum(1)
        self.gamma_slider.setMaximum(100)
        self.gamma_slider.setProperty("value", 10)
        self.gamma_slider.setOrientation(QtCore.Qt.Vertical)
        self.gamma_slider.setObjectName("gamma_slider")
        self.gamma_label = QtWidgets.QLabel(Dialog)
        self.gamma_label.setGeometry(QtCore.QRect(870, 50, 51, 31))
        self.gamma_label.setObjectName("gamma_label")
        self.gain_slider = QtWidgets.QSlider(Dialog)
        self.gain_slider.setEnabled(False)
        self.gain_slider.setGeometry(QtCore.QRect(920, 90, 22, 681))
        self.gain_slider.setMinimum(1)
        self.gain_slider.setMaximum(100)
        self.gain_slider.setProperty("value", 10)
        self.gain_slider.setOrientation(QtCore.Qt.Vertical)
        self.gain_slider.setObjectName("gain_slider")
        self.gain_label = QtWidgets.QLabel(Dialog)
        self.gain_label.setGeometry(QtCore.QRect(920, 50, 31, 31))
        self.gain_label.setObjectName("gain_label")
        self.filter_slider = QtWidgets.QSlider(Dialog)
        self.filter_slider.setEnabled(False)
        self.filter_slider.setGeometry(QtCore.QRect(960, 90, 22, 681))
        self.filter_slider.setMinimum(1)
        self.filter_slider.setMaximum(10)
        self.filter_slider.setPageStep(3)
        self.filter_slider.setProperty("value", 1)
        self.filter_slider.setOrientation(QtCore.Qt.Vertical)
        self.filter_slider.setObjectName("filter_slider")
        self.filter_label = QtWidgets.QLabel(Dialog)
        self.filter_label.setGeometry(QtCore.QRect(960, 50, 31, 31))
        self.filter_label.setObjectName("filter_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dicom3D_viewer"))
        self.load_button.setText(_translate("Dialog", "Load"))
        self.gamma_label.setText(_translate("Dialog", "Gamma"))
        self.gain_label.setText(_translate("Dialog", "Gain"))
        self.filter_label.setText(_translate("Dialog", "Filter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

